name: GH Pages

on:
  push:
    paths:
      # Trying to run whenever the version is changed.
      # There is probably a smarter way to do this.
      - 'package.json'
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: jekyll-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
