name: GH Pages

on:
  push:
    paths:
      # Trying to run whenever the version is changed.
      # There is probably a smarter way to do this.
      - 'package.json'
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: jekyll-build
    environment: github-pages
    url: $
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
