name: Release

on:
  push:
    paths:
      # Trying to run whenever the version is changed.
      # There is probably a smarter way to do this.
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Github Package Registry
        run: |
          npm config set @dk-books:registry https://npm.pkg.github.com
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GPR_ACCESS_TOKEN_APRIL_2023}}" > ~/.npmrc
      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@dk-books"
      - name: Install modules
        run: npm ci
      - name: Build
        run: npm run build

      - name: Publish
        run: npm run release -- --gh-pages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN_APRIL_2023 }}
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: '/jekyll-theme-yat'  # Default is empty